//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogClient.BlogService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://bearhuchao.top/")]
    [System.SerializableAttribute()]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        private int BlogsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Blogs {
            get {
                return this.BlogsField;
            }
            set {
                if ((this.BlogsField.Equals(value) != true)) {
                    this.BlogsField = value;
                    this.RaisePropertyChanged("Blogs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlogInfo", Namespace="http://bearhuchao.top/")]
    [System.SerializableAttribute()]
    public partial class BlogInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        private int CommentNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int CommentNumber {
            get {
                return this.CommentNumberField;
            }
            set {
                if ((this.CommentNumberField.Equals(value) != true)) {
                    this.CommentNumberField = value;
                    this.RaisePropertyChanged("CommentNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlogDetail", Namespace="http://bearhuchao.top/")]
    [System.SerializableAttribute()]
    public partial class BlogDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlogClient.BlogService.CommentInfo[] CommentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateTimeField, value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public BlogClient.BlogService.CommentInfo[] Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommentInfo", Namespace="http://bearhuchao.top/")]
    [System.SerializableAttribute()]
    public partial class CommentInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bearhuchao.top/", ConfigurationName="BlogService.BlogServiceSoap")]
    public interface BlogServiceSoap {
        
        // CODEGEN: 命名空间 http://bearhuchao.top/ 的元素名称 username 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bearhuchao.top/AddUser", ReplyAction="*")]
        BlogClient.BlogService.AddUserResponse AddUser(BlogClient.BlogService.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bearhuchao.top/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogClient.BlogService.AddUserResponse> AddUserAsync(BlogClient.BlogService.AddUserRequest request);
        
        // CODEGEN: 命名空间 http://bearhuchao.top/ 的元素名称 username 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bearhuchao.top/GetUser", ReplyAction="*")]
        BlogClient.BlogService.GetUserResponse GetUser(BlogClient.BlogService.GetUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bearhuchao.top/GetUser", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogClient.BlogService.GetUserResponse> GetUserAsync(BlogClient.BlogService.GetUserRequest request);
        
        // CODEGEN: 命名空间 http://bearhuchao.top/ 的元素名称 GetUsersResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bearhuchao.top/GetUsers", ReplyAction="*")]
        BlogClient.BlogService.GetUsersResponse GetUsers(BlogClient.BlogService.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bearhuchao.top/GetUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogClient.BlogService.GetUsersResponse> GetUsersAsync(BlogClient.BlogService.GetUsersRequest request);
        
        // CODEGEN: 命名空间 http://bearhuchao.top/ 的元素名称 title 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bearhuchao.top/AddBlog", ReplyAction="*")]
        BlogClient.BlogService.AddBlogResponse AddBlog(BlogClient.BlogService.AddBlogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bearhuchao.top/AddBlog", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogClient.BlogService.AddBlogResponse> AddBlogAsync(BlogClient.BlogService.AddBlogRequest request);
        
        // CODEGEN: 命名空间 http://bearhuchao.top/ 的元素名称 id 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bearhuchao.top/GetBlogs", ReplyAction="*")]
        BlogClient.BlogService.GetBlogsResponse GetBlogs(BlogClient.BlogService.GetBlogsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bearhuchao.top/GetBlogs", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogClient.BlogService.GetBlogsResponse> GetBlogsAsync(BlogClient.BlogService.GetBlogsRequest request);
        
        // CODEGEN: 命名空间 http://bearhuchao.top/ 的元素名称 id 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bearhuchao.top/GetBlogDetail", ReplyAction="*")]
        BlogClient.BlogService.GetBlogDetailResponse GetBlogDetail(BlogClient.BlogService.GetBlogDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bearhuchao.top/GetBlogDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogClient.BlogService.GetBlogDetailResponse> GetBlogDetailAsync(BlogClient.BlogService.GetBlogDetailRequest request);
        
        // CODEGEN: 命名空间 http://bearhuchao.top/ 的元素名称 BlogId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bearhuchao.top/GetBlogComments", ReplyAction="*")]
        BlogClient.BlogService.GetBlogCommentsResponse GetBlogComments(BlogClient.BlogService.GetBlogCommentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bearhuchao.top/GetBlogComments", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogClient.BlogService.GetBlogCommentsResponse> GetBlogCommentsAsync(BlogClient.BlogService.GetBlogCommentsRequest request);
        
        // CODEGEN: 命名空间 http://bearhuchao.top/ 的元素名称 BlogId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bearhuchao.top/AddBlogComment", ReplyAction="*")]
        BlogClient.BlogService.AddBlogCommentResponse AddBlogComment(BlogClient.BlogService.AddBlogCommentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bearhuchao.top/AddBlogComment", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogClient.BlogService.AddBlogCommentResponse> AddBlogCommentAsync(BlogClient.BlogService.AddBlogCommentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser", Namespace="http://bearhuchao.top/", Order=0)]
        public BlogClient.BlogService.AddUserRequestBody Body;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(BlogClient.BlogService.AddUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bearhuchao.top/")]
    public partial class AddUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public AddUserRequestBody() {
        }
        
        public AddUserRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserResponse", Namespace="http://bearhuchao.top/", Order=0)]
        public BlogClient.BlogService.AddUserResponseBody Body;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(BlogClient.BlogService.AddUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bearhuchao.top/")]
    public partial class AddUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddUserResult;
        
        public AddUserResponseBody() {
        }
        
        public AddUserResponseBody(string AddUserResult) {
            this.AddUserResult = AddUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUser", Namespace="http://bearhuchao.top/", Order=0)]
        public BlogClient.BlogService.GetUserRequestBody Body;
        
        public GetUserRequest() {
        }
        
        public GetUserRequest(BlogClient.BlogService.GetUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bearhuchao.top/")]
    public partial class GetUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetUserRequestBody() {
        }
        
        public GetUserRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserResponse", Namespace="http://bearhuchao.top/", Order=0)]
        public BlogClient.BlogService.GetUserResponseBody Body;
        
        public GetUserResponse() {
        }
        
        public GetUserResponse(BlogClient.BlogService.GetUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bearhuchao.top/")]
    public partial class GetUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogClient.BlogService.UserInfo GetUserResult;
        
        public GetUserResponseBody() {
        }
        
        public GetUserResponseBody(BlogClient.BlogService.UserInfo GetUserResult) {
            this.GetUserResult = GetUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsers", Namespace="http://bearhuchao.top/", Order=0)]
        public BlogClient.BlogService.GetUsersRequestBody Body;
        
        public GetUsersRequest() {
        }
        
        public GetUsersRequest(BlogClient.BlogService.GetUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUsersRequestBody {
        
        public GetUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersResponse", Namespace="http://bearhuchao.top/", Order=0)]
        public BlogClient.BlogService.GetUsersResponseBody Body;
        
        public GetUsersResponse() {
        }
        
        public GetUsersResponse(BlogClient.BlogService.GetUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bearhuchao.top/")]
    public partial class GetUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogClient.BlogService.UserInfo[] GetUsersResult;
        
        public GetUsersResponseBody() {
        }
        
        public GetUsersResponseBody(BlogClient.BlogService.UserInfo[] GetUsersResult) {
            this.GetUsersResult = GetUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBlogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBlog", Namespace="http://bearhuchao.top/", Order=0)]
        public BlogClient.BlogService.AddBlogRequestBody Body;
        
        public AddBlogRequest() {
        }
        
        public AddBlogRequest(BlogClient.BlogService.AddBlogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bearhuchao.top/")]
    public partial class AddBlogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string author;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string content;
        
        public AddBlogRequestBody() {
        }
        
        public AddBlogRequestBody(string title, string author, string content) {
            this.title = title;
            this.author = author;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBlogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBlogResponse", Namespace="http://bearhuchao.top/", Order=0)]
        public BlogClient.BlogService.AddBlogResponseBody Body;
        
        public AddBlogResponse() {
        }
        
        public AddBlogResponse(BlogClient.BlogService.AddBlogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bearhuchao.top/")]
    public partial class AddBlogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddBlogResult;
        
        public AddBlogResponseBody() {
        }
        
        public AddBlogResponseBody(string AddBlogResult) {
            this.AddBlogResult = AddBlogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlogsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlogs", Namespace="http://bearhuchao.top/", Order=0)]
        public BlogClient.BlogService.GetBlogsRequestBody Body;
        
        public GetBlogsRequest() {
        }
        
        public GetBlogsRequest(BlogClient.BlogService.GetBlogsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bearhuchao.top/")]
    public partial class GetBlogsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetBlogsRequestBody() {
        }
        
        public GetBlogsRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlogsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlogsResponse", Namespace="http://bearhuchao.top/", Order=0)]
        public BlogClient.BlogService.GetBlogsResponseBody Body;
        
        public GetBlogsResponse() {
        }
        
        public GetBlogsResponse(BlogClient.BlogService.GetBlogsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bearhuchao.top/")]
    public partial class GetBlogsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogClient.BlogService.BlogInfo[] GetBlogsResult;
        
        public GetBlogsResponseBody() {
        }
        
        public GetBlogsResponseBody(BlogClient.BlogService.BlogInfo[] GetBlogsResult) {
            this.GetBlogsResult = GetBlogsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlogDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlogDetail", Namespace="http://bearhuchao.top/", Order=0)]
        public BlogClient.BlogService.GetBlogDetailRequestBody Body;
        
        public GetBlogDetailRequest() {
        }
        
        public GetBlogDetailRequest(BlogClient.BlogService.GetBlogDetailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bearhuchao.top/")]
    public partial class GetBlogDetailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetBlogDetailRequestBody() {
        }
        
        public GetBlogDetailRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlogDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlogDetailResponse", Namespace="http://bearhuchao.top/", Order=0)]
        public BlogClient.BlogService.GetBlogDetailResponseBody Body;
        
        public GetBlogDetailResponse() {
        }
        
        public GetBlogDetailResponse(BlogClient.BlogService.GetBlogDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bearhuchao.top/")]
    public partial class GetBlogDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogClient.BlogService.BlogDetail GetBlogDetailResult;
        
        public GetBlogDetailResponseBody() {
        }
        
        public GetBlogDetailResponseBody(BlogClient.BlogService.BlogDetail GetBlogDetailResult) {
            this.GetBlogDetailResult = GetBlogDetailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlogCommentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlogComments", Namespace="http://bearhuchao.top/", Order=0)]
        public BlogClient.BlogService.GetBlogCommentsRequestBody Body;
        
        public GetBlogCommentsRequest() {
        }
        
        public GetBlogCommentsRequest(BlogClient.BlogService.GetBlogCommentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bearhuchao.top/")]
    public partial class GetBlogCommentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BlogId;
        
        public GetBlogCommentsRequestBody() {
        }
        
        public GetBlogCommentsRequestBody(string BlogId) {
            this.BlogId = BlogId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlogCommentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlogCommentsResponse", Namespace="http://bearhuchao.top/", Order=0)]
        public BlogClient.BlogService.GetBlogCommentsResponseBody Body;
        
        public GetBlogCommentsResponse() {
        }
        
        public GetBlogCommentsResponse(BlogClient.BlogService.GetBlogCommentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bearhuchao.top/")]
    public partial class GetBlogCommentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogClient.BlogService.CommentInfo[] GetBlogCommentsResult;
        
        public GetBlogCommentsResponseBody() {
        }
        
        public GetBlogCommentsResponseBody(BlogClient.BlogService.CommentInfo[] GetBlogCommentsResult) {
            this.GetBlogCommentsResult = GetBlogCommentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBlogCommentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBlogComment", Namespace="http://bearhuchao.top/", Order=0)]
        public BlogClient.BlogService.AddBlogCommentRequestBody Body;
        
        public AddBlogCommentRequest() {
        }
        
        public AddBlogCommentRequest(BlogClient.BlogService.AddBlogCommentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bearhuchao.top/")]
    public partial class AddBlogCommentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BlogId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string author;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string content;
        
        public AddBlogCommentRequestBody() {
        }
        
        public AddBlogCommentRequestBody(string BlogId, string author, string content) {
            this.BlogId = BlogId;
            this.author = author;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBlogCommentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBlogCommentResponse", Namespace="http://bearhuchao.top/", Order=0)]
        public BlogClient.BlogService.AddBlogCommentResponseBody Body;
        
        public AddBlogCommentResponse() {
        }
        
        public AddBlogCommentResponse(BlogClient.BlogService.AddBlogCommentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bearhuchao.top/")]
    public partial class AddBlogCommentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddBlogCommentResult;
        
        public AddBlogCommentResponseBody() {
        }
        
        public AddBlogCommentResponseBody(string AddBlogCommentResult) {
            this.AddBlogCommentResult = AddBlogCommentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BlogServiceSoapChannel : BlogClient.BlogService.BlogServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlogServiceSoapClient : System.ServiceModel.ClientBase<BlogClient.BlogService.BlogServiceSoap>, BlogClient.BlogService.BlogServiceSoap {
        
        public BlogServiceSoapClient() {
        }
        
        public BlogServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlogServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlogServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlogServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogClient.BlogService.AddUserResponse BlogClient.BlogService.BlogServiceSoap.AddUser(BlogClient.BlogService.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public string AddUser(string username) {
            BlogClient.BlogService.AddUserRequest inValue = new BlogClient.BlogService.AddUserRequest();
            inValue.Body = new BlogClient.BlogService.AddUserRequestBody();
            inValue.Body.username = username;
            BlogClient.BlogService.AddUserResponse retVal = ((BlogClient.BlogService.BlogServiceSoap)(this)).AddUser(inValue);
            return retVal.Body.AddUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogClient.BlogService.AddUserResponse> BlogClient.BlogService.BlogServiceSoap.AddUserAsync(BlogClient.BlogService.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogClient.BlogService.AddUserResponse> AddUserAsync(string username) {
            BlogClient.BlogService.AddUserRequest inValue = new BlogClient.BlogService.AddUserRequest();
            inValue.Body = new BlogClient.BlogService.AddUserRequestBody();
            inValue.Body.username = username;
            return ((BlogClient.BlogService.BlogServiceSoap)(this)).AddUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogClient.BlogService.GetUserResponse BlogClient.BlogService.BlogServiceSoap.GetUser(BlogClient.BlogService.GetUserRequest request) {
            return base.Channel.GetUser(request);
        }
        
        public BlogClient.BlogService.UserInfo GetUser(string username) {
            BlogClient.BlogService.GetUserRequest inValue = new BlogClient.BlogService.GetUserRequest();
            inValue.Body = new BlogClient.BlogService.GetUserRequestBody();
            inValue.Body.username = username;
            BlogClient.BlogService.GetUserResponse retVal = ((BlogClient.BlogService.BlogServiceSoap)(this)).GetUser(inValue);
            return retVal.Body.GetUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogClient.BlogService.GetUserResponse> BlogClient.BlogService.BlogServiceSoap.GetUserAsync(BlogClient.BlogService.GetUserRequest request) {
            return base.Channel.GetUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogClient.BlogService.GetUserResponse> GetUserAsync(string username) {
            BlogClient.BlogService.GetUserRequest inValue = new BlogClient.BlogService.GetUserRequest();
            inValue.Body = new BlogClient.BlogService.GetUserRequestBody();
            inValue.Body.username = username;
            return ((BlogClient.BlogService.BlogServiceSoap)(this)).GetUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogClient.BlogService.GetUsersResponse BlogClient.BlogService.BlogServiceSoap.GetUsers(BlogClient.BlogService.GetUsersRequest request) {
            return base.Channel.GetUsers(request);
        }
        
        public BlogClient.BlogService.UserInfo[] GetUsers() {
            BlogClient.BlogService.GetUsersRequest inValue = new BlogClient.BlogService.GetUsersRequest();
            inValue.Body = new BlogClient.BlogService.GetUsersRequestBody();
            BlogClient.BlogService.GetUsersResponse retVal = ((BlogClient.BlogService.BlogServiceSoap)(this)).GetUsers(inValue);
            return retVal.Body.GetUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogClient.BlogService.GetUsersResponse> BlogClient.BlogService.BlogServiceSoap.GetUsersAsync(BlogClient.BlogService.GetUsersRequest request) {
            return base.Channel.GetUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogClient.BlogService.GetUsersResponse> GetUsersAsync() {
            BlogClient.BlogService.GetUsersRequest inValue = new BlogClient.BlogService.GetUsersRequest();
            inValue.Body = new BlogClient.BlogService.GetUsersRequestBody();
            return ((BlogClient.BlogService.BlogServiceSoap)(this)).GetUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogClient.BlogService.AddBlogResponse BlogClient.BlogService.BlogServiceSoap.AddBlog(BlogClient.BlogService.AddBlogRequest request) {
            return base.Channel.AddBlog(request);
        }
        
        public string AddBlog(string title, string author, string content) {
            BlogClient.BlogService.AddBlogRequest inValue = new BlogClient.BlogService.AddBlogRequest();
            inValue.Body = new BlogClient.BlogService.AddBlogRequestBody();
            inValue.Body.title = title;
            inValue.Body.author = author;
            inValue.Body.content = content;
            BlogClient.BlogService.AddBlogResponse retVal = ((BlogClient.BlogService.BlogServiceSoap)(this)).AddBlog(inValue);
            return retVal.Body.AddBlogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogClient.BlogService.AddBlogResponse> BlogClient.BlogService.BlogServiceSoap.AddBlogAsync(BlogClient.BlogService.AddBlogRequest request) {
            return base.Channel.AddBlogAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogClient.BlogService.AddBlogResponse> AddBlogAsync(string title, string author, string content) {
            BlogClient.BlogService.AddBlogRequest inValue = new BlogClient.BlogService.AddBlogRequest();
            inValue.Body = new BlogClient.BlogService.AddBlogRequestBody();
            inValue.Body.title = title;
            inValue.Body.author = author;
            inValue.Body.content = content;
            return ((BlogClient.BlogService.BlogServiceSoap)(this)).AddBlogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogClient.BlogService.GetBlogsResponse BlogClient.BlogService.BlogServiceSoap.GetBlogs(BlogClient.BlogService.GetBlogsRequest request) {
            return base.Channel.GetBlogs(request);
        }
        
        public BlogClient.BlogService.BlogInfo[] GetBlogs(string id) {
            BlogClient.BlogService.GetBlogsRequest inValue = new BlogClient.BlogService.GetBlogsRequest();
            inValue.Body = new BlogClient.BlogService.GetBlogsRequestBody();
            inValue.Body.id = id;
            BlogClient.BlogService.GetBlogsResponse retVal = ((BlogClient.BlogService.BlogServiceSoap)(this)).GetBlogs(inValue);
            return retVal.Body.GetBlogsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogClient.BlogService.GetBlogsResponse> BlogClient.BlogService.BlogServiceSoap.GetBlogsAsync(BlogClient.BlogService.GetBlogsRequest request) {
            return base.Channel.GetBlogsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogClient.BlogService.GetBlogsResponse> GetBlogsAsync(string id) {
            BlogClient.BlogService.GetBlogsRequest inValue = new BlogClient.BlogService.GetBlogsRequest();
            inValue.Body = new BlogClient.BlogService.GetBlogsRequestBody();
            inValue.Body.id = id;
            return ((BlogClient.BlogService.BlogServiceSoap)(this)).GetBlogsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogClient.BlogService.GetBlogDetailResponse BlogClient.BlogService.BlogServiceSoap.GetBlogDetail(BlogClient.BlogService.GetBlogDetailRequest request) {
            return base.Channel.GetBlogDetail(request);
        }
        
        public BlogClient.BlogService.BlogDetail GetBlogDetail(string id) {
            BlogClient.BlogService.GetBlogDetailRequest inValue = new BlogClient.BlogService.GetBlogDetailRequest();
            inValue.Body = new BlogClient.BlogService.GetBlogDetailRequestBody();
            inValue.Body.id = id;
            BlogClient.BlogService.GetBlogDetailResponse retVal = ((BlogClient.BlogService.BlogServiceSoap)(this)).GetBlogDetail(inValue);
            return retVal.Body.GetBlogDetailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogClient.BlogService.GetBlogDetailResponse> BlogClient.BlogService.BlogServiceSoap.GetBlogDetailAsync(BlogClient.BlogService.GetBlogDetailRequest request) {
            return base.Channel.GetBlogDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogClient.BlogService.GetBlogDetailResponse> GetBlogDetailAsync(string id) {
            BlogClient.BlogService.GetBlogDetailRequest inValue = new BlogClient.BlogService.GetBlogDetailRequest();
            inValue.Body = new BlogClient.BlogService.GetBlogDetailRequestBody();
            inValue.Body.id = id;
            return ((BlogClient.BlogService.BlogServiceSoap)(this)).GetBlogDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogClient.BlogService.GetBlogCommentsResponse BlogClient.BlogService.BlogServiceSoap.GetBlogComments(BlogClient.BlogService.GetBlogCommentsRequest request) {
            return base.Channel.GetBlogComments(request);
        }
        
        public BlogClient.BlogService.CommentInfo[] GetBlogComments(string BlogId) {
            BlogClient.BlogService.GetBlogCommentsRequest inValue = new BlogClient.BlogService.GetBlogCommentsRequest();
            inValue.Body = new BlogClient.BlogService.GetBlogCommentsRequestBody();
            inValue.Body.BlogId = BlogId;
            BlogClient.BlogService.GetBlogCommentsResponse retVal = ((BlogClient.BlogService.BlogServiceSoap)(this)).GetBlogComments(inValue);
            return retVal.Body.GetBlogCommentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogClient.BlogService.GetBlogCommentsResponse> BlogClient.BlogService.BlogServiceSoap.GetBlogCommentsAsync(BlogClient.BlogService.GetBlogCommentsRequest request) {
            return base.Channel.GetBlogCommentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogClient.BlogService.GetBlogCommentsResponse> GetBlogCommentsAsync(string BlogId) {
            BlogClient.BlogService.GetBlogCommentsRequest inValue = new BlogClient.BlogService.GetBlogCommentsRequest();
            inValue.Body = new BlogClient.BlogService.GetBlogCommentsRequestBody();
            inValue.Body.BlogId = BlogId;
            return ((BlogClient.BlogService.BlogServiceSoap)(this)).GetBlogCommentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogClient.BlogService.AddBlogCommentResponse BlogClient.BlogService.BlogServiceSoap.AddBlogComment(BlogClient.BlogService.AddBlogCommentRequest request) {
            return base.Channel.AddBlogComment(request);
        }
        
        public string AddBlogComment(string BlogId, string author, string content) {
            BlogClient.BlogService.AddBlogCommentRequest inValue = new BlogClient.BlogService.AddBlogCommentRequest();
            inValue.Body = new BlogClient.BlogService.AddBlogCommentRequestBody();
            inValue.Body.BlogId = BlogId;
            inValue.Body.author = author;
            inValue.Body.content = content;
            BlogClient.BlogService.AddBlogCommentResponse retVal = ((BlogClient.BlogService.BlogServiceSoap)(this)).AddBlogComment(inValue);
            return retVal.Body.AddBlogCommentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogClient.BlogService.AddBlogCommentResponse> BlogClient.BlogService.BlogServiceSoap.AddBlogCommentAsync(BlogClient.BlogService.AddBlogCommentRequest request) {
            return base.Channel.AddBlogCommentAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogClient.BlogService.AddBlogCommentResponse> AddBlogCommentAsync(string BlogId, string author, string content) {
            BlogClient.BlogService.AddBlogCommentRequest inValue = new BlogClient.BlogService.AddBlogCommentRequest();
            inValue.Body = new BlogClient.BlogService.AddBlogCommentRequestBody();
            inValue.Body.BlogId = BlogId;
            inValue.Body.author = author;
            inValue.Body.content = content;
            return ((BlogClient.BlogService.BlogServiceSoap)(this)).AddBlogCommentAsync(inValue);
        }
    }
}
